# Generated by Django 4.0.5 on 2022-06-15 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futbolec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campeonatosequipo',
            name='campeonato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equiposs', to='futbolec.campeonato'),
        ),
        migrations.AlterField(
            model_name='campeonatosequipo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campeonatoss', to='futbolec.equipo'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='numero',
            field=models.IntegerField(verbose_name='Numero Camiseta'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='sueldo',
            field=models.FloatField(verbose_name='Sueldo'),
        ),
    ]
