# Generated by Django 4.0.5 on 2022-06-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolec', '0002_alter_campeonatosequipo_campeonato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='siglas',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='twitter',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
